-- Corrige persistência e visibilidade de alunos sem apagar dados existentes.

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, nome, email, role)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'nome', ''), split_part(NEW.email, '@', 1)),
    COALESCE(NEW.email, ''),
    CASE WHEN NEW.raw_user_meta_data->>'role' = 'admin' THEN 'admin' ELSE 'aluno' END
  )
  ON CONFLICT (id) DO UPDATE SET
    nome = CASE WHEN public.profiles.nome = '' THEN EXCLUDED.nome ELSE public.profiles.nome END,
    email = EXCLUDED.email;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

INSERT INTO public.profiles (id, nome, email, role, created_at)
SELECT
  users.id,
  COALESCE(NULLIF(users.raw_user_meta_data->>'nome', ''), split_part(users.email, '@', 1)),
  COALESCE(users.email, ''),
  CASE WHEN users.raw_user_meta_data->>'role' = 'admin' THEN 'admin' ELSE 'aluno' END,
  users.created_at
FROM auth.users AS users
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.ensure_my_profile()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  current_id UUID := auth.uid();
  claims JSONB := auth.jwt();
BEGIN
  IF current_id IS NULL THEN
    RAISE EXCEPTION 'Usuário não autenticado';
  END IF;

  INSERT INTO public.profiles (id, nome, email, role)
  VALUES (
    current_id,
    COALESCE(
      NULLIF(claims->'user_metadata'->>'nome', ''),
      split_part(COALESCE(claims->>'email', ''), '@', 1)
    ),
    COALESCE(claims->>'email', ''),
    CASE WHEN claims->'user_metadata'->>'role' = 'admin' THEN 'admin' ELSE 'aluno' END
  )
  ON CONFLICT (id) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.ensure_my_profile() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ensure_my_profile() TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_ensure_profile(
  target_id UUID,
  target_email TEXT,
  target_nome TEXT,
  target_role TEXT DEFAULT 'aluno'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Acesso administrativo necessário';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = target_id) THEN
    RAISE EXCEPTION 'Conta de autenticação não encontrada';
  END IF;

  INSERT INTO public.profiles (id, nome, email, role)
  VALUES (
    target_id,
    COALESCE(NULLIF(trim(target_nome), ''), split_part(target_email, '@', 1)),
    target_email,
    CASE WHEN target_role = 'admin' THEN 'admin' ELSE 'aluno' END
  )
  ON CONFLICT (id) DO UPDATE SET
    nome = EXCLUDED.nome,
    email = EXCLUDED.email,
    role = EXCLUDED.role;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_ensure_profile(UUID, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_ensure_profile(UUID, TEXT, TEXT, TEXT) TO authenticated;

CREATE TABLE IF NOT EXISTS public.login_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  logged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS login_history_user_logged_at_idx
  ON public.login_history (user_id, logged_at DESC);

ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura do próprio profile" ON public.profiles;
DROP POLICY IF EXISTS "Edição do próprio profile" ON public.profiles;
DROP POLICY IF EXISTS "Admin – profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admin - profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admin – gerenciar profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admin - gerenciar profiles" ON public.profiles;
DROP POLICY IF EXISTS "Profile próprio ou administração" ON public.profiles;
DROP POLICY IF EXISTS "Atualizar profile próprio" ON public.profiles;
DROP POLICY IF EXISTS "Admin inserir profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admin excluir profiles" ON public.profiles;

CREATE POLICY "Profile próprio ou administração"
ON public.profiles FOR SELECT
USING (id = auth.uid() OR public.is_admin());

CREATE POLICY "Atualizar profile próprio"
ON public.profiles FOR UPDATE
USING (id = auth.uid() OR public.is_admin())
WITH CHECK (id = auth.uid() OR public.is_admin());

CREATE POLICY "Admin inserir profiles"
ON public.profiles FOR INSERT
WITH CHECK (public.is_admin());

CREATE POLICY "Admin excluir profiles"
ON public.profiles FOR DELETE
USING (public.is_admin());

DROP POLICY IF EXISTS "Leitura próprio progresso" ON public.progressos;
DROP POLICY IF EXISTS "Inserir próprio progresso" ON public.progressos;
DROP POLICY IF EXISTS "Atualizar próprio progresso" ON public.progressos;
DROP POLICY IF EXISTS "Admin – progressos" ON public.progressos;
DROP POLICY IF EXISTS "Admin - progressos" ON public.progressos;
DROP POLICY IF EXISTS "Progresso próprio ou administração" ON public.progressos;
DROP POLICY IF EXISTS "Inserir progresso próprio" ON public.progressos;
DROP POLICY IF EXISTS "Atualizar progresso próprio" ON public.progressos;
DROP POLICY IF EXISTS "Admin excluir progressos" ON public.progressos;

CREATE POLICY "Progresso próprio ou administração"
ON public.progressos FOR SELECT
USING (user_id = auth.uid() OR public.is_admin());

CREATE POLICY "Inserir progresso próprio"
ON public.progressos FOR INSERT
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Atualizar progresso próprio"
ON public.progressos FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Admin excluir progressos"
ON public.progressos FOR DELETE
USING (public.is_admin());

DROP POLICY IF EXISTS "Inserir próprio login" ON public.login_history;
DROP POLICY IF EXISTS "Ler próprios logins" ON public.login_history;
DROP POLICY IF EXISTS "Admin ler logins" ON public.login_history;

CREATE POLICY "Inserir próprio login"
ON public.login_history FOR INSERT
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Ler próprios logins"
ON public.login_history FOR SELECT
USING (user_id = auth.uid() OR public.is_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.progressos TO authenticated;
GRANT SELECT, INSERT ON public.login_history TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.login_history_id_seq TO authenticated;
